let SEASON_SENIOR_A = [
  // Jornada 1
  {
    imgURL: "public/img/escudos/cd_tenerife.png",
    date: "Sep 07, 2024 17:00:00",
    shortDate: "07/09/24",
    isLocal: false,
    result: "2-2",
    mapsURL: "",
    liveURL: "",
    hashtag: "#OLYMPIATENERIFE",
  },
  // Jornada 2
  {
    imgURL: "public/img/escudos/caceres.png",
    date: "Sep 15, 2024 19:00:00",
    shortDate: "15/09/24",
    isLocal: true,
    result: "2-0",
    mapsURL: "https://goo.gl/maps/exjzXaRCWYzKmyfTA",
    liveURL: "",
    hashtag: "#OLYMPIACACERES",
  },
  // Jornada 3
  {
    imgURL: "public/img/escudos/guiniguada.png",
    date: "Sep 22, 2024 10:00:00",
    shortDate: "22/09/24",
    isLocal: false,
    result: "0-2",
    mapsURL: "",
    liveURL: "",
    hashtag: "#OLYMPIAGUINIGUADA",
  },
  // Jornada 4
  {
    imgURL: "public/img/escudos/valencia.png",
    date: "Sep 29, 2024 17:00:00",
    shortDate: "29/09/24",
    isLocal: true,
    result: "2-0",
    mapsURL: "https://goo.gl/maps/exjzXaRCWYzKmyfTA",
    liveURL: "",
    hashtag: "#OLYMPIAVALENCIA",
  },
  // Jornada 5
  {
    imgURL: "public/img/escudos/la_destila.png",
    date: "Oct 06, 2024 19:00:00",
    shortDate: "06/10/24",
    isLocal: false,
    result: "0-6",
    mapsURL: "",
    liveURL: "",
    hashtag: "#OLYMPIALADESTILA",
  },
  // Jornada 6
  {
    imgURL: "public/img/escudos/madrid_cf.png",
    date: "Oct 13, 2024 19:00:00",
    shortDate: "13/10/24",
    isLocal: true,
    result: "1-0",
    mapsURL: "https://goo.gl/maps/exjzXaRCWYzKmyfTA",
    liveURL: "",
    hashtag: "#OLYMPIAMADRIDCF",
  },
  // Jornada 7
  {
    imgURL: "public/img/escudos/costa_adeje.png",
    date: "Oct 20, 2024 19:00:00",
    shortDate: "20/10/24",
    isLocal: false,
    result: "2-1",
    mapsURL: "",
    liveURL: "",
    hashtag: "#OLYMPIACOSTAADEJE",
  },
  // Jornada 8
  {
    imgURL: "public/img/escudos/femarguin.png",
    date: "Oct 27, 2024 17:00:00",
    shortDate: "27/10/24",
    isLocal: true,
    result: "3-0",
    mapsURL: "https://goo.gl/maps/exjzXaRCWYzKmyfTA",
    liveURL: "",
    hashtag: "#OLYMPIAFEMARGUIN",
  },
  // Jornada 9
  {
    imgURL: "public/img/escudos/cordoba.png",
    date: "Nov 02, 2024 13:00:00",
    shortDate: "02/11/24",
    isLocal: false,
    result: "0-1",
    mapsURL: "",
    liveURL: "",
    hashtag: "#OLYMPIACORDOBA",
  },
  // Jornada 10
  {
    imgURL: "public/img/escudos/malaga.png",
    date: "Nov 10, 2024 19:00:00",
    shortDate: "10/11/24",
    isLocal: true,
    result: "0-3",
    mapsURL: "https://goo.gl/maps/exjzXaRCWYzKmyfTA",
    liveURL: "",
    hashtag: "#OLYMPIAMALAGA",
  },
  // Jornada 11
  {
    imgURL: "public/img/escudos/levante.png",
    date: "Nov 17, 2024 19:00:00",
    shortDate: "17/11/24",
    isLocal: false,
    result: "4-3",
    mapsURL: "",
    liveURL: "",
    hashtag: "#OLYMPIALEVANTE",
  },
  // Jornada 12
  {
    imgURL: "public/img/escudos/real_union_tenerife.png",
    date: "Nov 24, 2024 19:00:00",
    shortDate: "24/11/24",
    isLocal: true,
    result: "0-2",
    mapsURL: "https://goo.gl/maps/exjzXaRCWYzKmyfTA",
    liveURL: "",
    hashtag: "#OLYMPIARUTENERIFE",
  },
  // Jornada 13
  {
    imgURL: "public/img/escudos/pozuelo.png",
    date: "Nov 30, 2024 19:00:00",
    shortDate: "30/11/24",
    isLocal: false,
    result: "2-2",
    mapsURL: "",
    liveURL: "",
    hashtag: "#OLYMPIAPOZUELO",
  },
  // Jornada 14
  {
    imgURL: "public/img/escudos/juan_grande.png",
    date: "Dec 08, 2024 17:00:00",
    shortDate: "08/12/24",
    isLocal: false,
    result: "2-2",
    mapsURL: "",
    liveURL: "",
    hashtag: "#OLYMPIAJUANGRANDE",
  },
  // Jornada 15
  {
    imgURL: "public/img/escudos/elche.png",
    date: "Dec 15, 2024 18:00:00",
    shortDate: "15/12/24",
    isLocal: true,
    result: "2-3",
    mapsURL: "https://goo.gl/maps/exjzXaRCWYzKmyfTA",
    liveURL: "",
    hashtag: "#OLYMPIAELCHE",
  },
  // Jornada 16
  {
    imgURL: "public/img/escudos/cd_tenerife.png",
    date: "Jan 12, 2025 17:00:00",
    shortDate: "12/01/25",
    isLocal: true,
    result: "0-2",
    mapsURL: "https://goo.gl/maps/exjzXaRCWYzKmyfTA",
    liveURL: "",
    hashtag: "#OLYMPIATENERIFE",
  },
  // Jornada 17
  {
    imgURL: "public/img/escudos/caceres.png",
    date: "Jan 19, 2025 17:00:00",
    shortDate: "19/01/25",
    isLocal: false,
    result: "1-1",
    mapsURL: "",
    liveURL: "",
    hashtag: "#OLYMPIACACERES",
  },
  // Jornada 18
  {
    imgURL: "public/img/escudos/guiniguada.png",
    date: "Feb 02, 2025 17:00:00",
    shortDate: "02/02/25",
    isLocal: true,
    result: "5-2",
    mapsURL: "https://goo.gl/maps/exjzXaRCWYzKmyfTA",
    liveURL: "",
    hashtag: "#OLYMPIAGUINIGUADA",
  },
  // Jornada 19
  {
    imgURL: "public/img/escudos/valencia.png",
    date: "Feb 08, 2025 16:00:00",
    shortDate: "08/02/25",
    isLocal: false,
    result: "0-2",
    mapsURL: "",
    liveURL: "",
    hashtag: "#OLYMPIAVALENCIA",
  },
  // Jornada 20
  {
    imgURL: "public/img/escudos/la_destila.png",
    date: "Feb 16, 2025 17:00:00",
    shortDate: "16/02/25",
    isLocal: true,
    result: "3-0",
    mapsURL: "https://goo.gl/maps/exjzXaRCWYzKmyfTA",
    liveURL: "",
    hashtag: "#OLYMPIALADESTILA",
  },
  // Jornada 21
  {
    imgURL: "public/img/escudos/madrid_cf.png",
    date: "Feb 23, 2025 17:00:00",
    shortDate: "23/02/25",
    isLocal: false,
    result: "1-0",
    mapsURL: "",
    liveURL: "",
    hashtag: "#OLYMPIAMADRIDCF",
  },
  // Jornada 22
  {
    imgURL: "public/img/escudos/costa_adeje.png",
    date: "Mar 02, 2025 17:00:00",
    shortDate: "02/03/25",
    isLocal: true,
    result: "1-0",
    mapsURL: "https://goo.gl/maps/exjzXaRCWYzKmyfTA",
    liveURL: "",
    hashtag: "#OLYMPIACOSTAADEJE",
  },
  // Jornada 23
  {
    imgURL: "public/img/escudos/femarguin.png",
    date: "Mar 09, 2025 17:00:00",
    shortDate: "09/03/25",
    isLocal: false,
    result: "1-2",
    mapsURL: "",
    liveURL: "",
    hashtag: "#OLYMPIAFEMARGUIN",
  },
  // Jornada 24
  {
    imgURL: "public/img/escudos/cordoba.png",
    date: "Mar 16, 2025 17:00:00",
    shortDate: "16/03/25",
    isLocal: true,
    result: "1-0",
    mapsURL: "https://goo.gl/maps/exjzXaRCWYzKmyfTA",
    liveURL: "",
    hashtag: "#OLYMPIACORDOBA",
  },
  // Jornada 25
  {
    imgURL: "public/img/escudos/malaga.png",
    date: "Mar 23, 2025 17:00:00",
    shortDate: "23/03/25",
    isLocal: false,
    result: "1-0",
    mapsURL: "",
    liveURL: "",
    hashtag: "#OLYMPIAMALAGA",
  },
  // Jornada 26
  {
    imgURL: "public/img/escudos/levante.png",
    date: "Mar 30, 2025 17:00:00",
    shortDate: "30/03/25",
    isLocal: true,
    result: "-",
    mapsURL: "https://goo.gl/maps/exjzXaRCWYzKmyfTA",
    liveURL: "",
    hashtag: "#OLYMPIALEVANTE",
  },
  // Jornada 27
  {
    imgURL: "public/img/escudos/real_union_tenerife.png",
    date: "Apr 13, 2025 17:00:00",
    shortDate: "13/04/25",
    isLocal: false,
    result: "-",
    mapsURL: "",
    liveURL: "",
    hashtag: "#OLYMPIARUTENERIFE",
  },
  // Jornada 28
  {
    imgURL: "public/img/escudos/pozuelo.png",
    date: "Apr 20, 2025 17:00:00",
    shortDate: "20/04/25",
    isLocal: true,
    result: "-",
    mapsURL: "https://goo.gl/maps/exjzXaRCWYzKmyfTA",
    liveURL: "",
    hashtag: "#OLYMPIAPOZUELO",
  },
  // Jornada 29
  {
    imgURL: "public/img/escudos/juan_grande.png",
    date: "Apr 27, 2025 17:00:00",
    shortDate: "27/04/25",
    isLocal: true,
    result: "-",
    mapsURL: "https://goo.gl/maps/exjzXaRCWYzKmyfTA",
    liveURL: "",
    hashtag: "#OLYMPIAJUANGRANDE",
  },
  // Jornada 30
  {
    imgURL: "public/img/escudos/elche.png",
    date: "May 04, 2025 17:00:00",
    shortDate: "04/05/25",
    isLocal: false,
    result: "-",
    mapsURL: "",
    liveURL: "",
    hashtag: "#OLYMPIAELCHE",
  },
];

export default SEASON_SENIOR_A;
